name: dynamic_animation
description: The dynamicTo function, an extension of AnimationController, enables spring-based animations.
version: 0.2.0
repository: https://github.com/MrHeer/dynamic_animation

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - animation
  - spring
